{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww35640\viewh21840\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 KUCOIN_API_KEY = "
\f1\fs24 \strokec2 68c9103cd12f8b0001f0c5fc
\f0\fs26 \strokec2 "\
KUCOIN_API_SECRET = "
\f1\fs24 \strokec2 54907fa2-df44-4c48-bc90-19eaba1898aa
\f0\fs26 \strokec2 "\
KUCOIN_API_PASSPHRASE = \'93Amirhossein@2212\'94\
}